### ISSUE TITLE
Option to use OpenAI instead of Azure OpenAI

### ISSUE THREAD

**Issue by shankarpandala** [Anaig/OpenAI-and-Cognitive-Search#3]
Due to restrictions from Microsoft, access to Azure OpenAI is not provided to individuals. It is available only to organizations that to with a review mechanism. 

So, People like me want to use OpenAI directly with rest of the Azure infrastructure like cognitive services, cognitive search etc.

**Comment by sissimonster** [comment]
Have you tried to replace the azure OpenAI key and endpoint to OpenAI's, does that work?

**Comment by shankarpandala** [comment]
@sissimonster It works

Closing this issue as it doesn't require any changes
